services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

        bind:
            AppBundle\Mailer\MailerInterface: '@AppBundle\Mailer\Mailer'
            AppBundle\Sms\SmsSenderInterface: '@AppBundle\Sms\SmsSender'

    AppBundle\:
        resource: "../../src/AppBundle/{Service, Role, Mailer, Sms}"

    AppBundle\DataFixtures\ORM\:
        resource: '../../src/AppBundle/DataFixtures/ORM'
        tags: ['doctrine.fixture.orm']

    AppBundle\Role\ReversedRoleHierarchy:
        arguments:
            $hierarchy: '%security.role_hierarchy.roles%'

    AppBundle\Service\AdmissionNotifier:
        arguments:
            $sendLimit: '%admission_notifier_limit%'

    guzzle.slack:
        class: GuzzleHttp\Client
        arguments:
            - { timeout: 2 }


    # Relying on service aut-registration is deprecateed, hence the creation of this:
    # It does remove the deprecation from symfony, but does it work as it should..?
    AppBundle\Sms\SlackSms:


    AppBundle\Sms\SmsSender:
        arguments:
            $env: '%kernel.environment%'

    AppBundle\Sms\GatewayAPI:
        arguments:
            $smsOptions: '%gateway_sms%'

    AppBundle\Service\LogService:
        arguments:
            $env: '%kernel.environment%'
            $monoLogger: '@logger'

    AppBundle\Mailer\Mailer:
        arguments:
            $env: '%kernel.environment%'

    AppBundle\Service\SurveyNotifier:
        arguments:
            $fromEmail: '%default_survey_email%'

    AppBundle\Service\GeoLocation:
        public: true
        arguments:
            $ipinfoToken: '%ipinfo_token%'
            $ignoredAsns: '%geo_ignored_asns%'
    AppBundle\Service\EmailSender:
        arguments:
            $defaultEmail: '%default_from_email%'
            $economyEmail: '%economy_email%'

    AppBundle\Service\SlackMessenger:
        arguments:
            $logger: '@logger'
            $notificationChannel: '%slack.notification_channel%'
            $logChannel: '%slack.log_channel%'
            $disableDelivery: '%slack.disable_delivery%'

    AppBundle\Service\FileUploader:
        arguments:
            $signatureFolder: '%signature_images%'
            $logoFolder: '%logo_images%'
            $receiptFolder: '%receipt_images%'
            $profilePhotoFolder: '%profile_photos%'
            $articleFolder: '%article_images%'
            $sponsorFolder: '%logo_images%'

    AppBundle\Service\RoleManager:
        public: true

    AppBundle\Service\SbsData:
        public: true

    AppBundle\Service\Sorter:
        public: true

    AppBundle\Service\AdmissionStatistics:
        public: true

    Symfony\Component\Serializer\NameConverter\NameConverterInterface: '@serializer.name_converter.camel_case_to_snake_case'
    Symfony\Component\PropertyInfo\PropertyTypeExtractorInterface: '@doctrine.orm.default_entity_manager.property_info_extractor'





    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        public: false
        tags: [serializer.normalizer]
